name="name:firstname"
mname="name:middlename"
lname="name:lastname"
course="xpath:/html/body/form/select"
gender="gender"
veh="vehicle1"
country="name:country code"
phone="name:phone"
address="tag:textarea"
email="id:email"
pwd="id:pass"
cpwd="id:repass"
lbtn="xpath:/html/body/form/input[12]"

